apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-orjywxyn
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-orjywxyn:a1e1c1c70023213570ff4eeadd60b6073d9260f8@sha256:be29a704f213963d0e43d86ef86fea05b5f8b1bf8d8c268da51a9ba572aab188
          name: container-image
